before_build:
  - nuget restore
after_build:
- cmd: >-
    nuget pack Jirapi.csproj -Build -IncludeReferencedProjects -Prop Configuration=Release
    appveyor PushArtifact *.nupkg
artifacts:
  - path: '**\Jirapi*.nupkg'
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  project: Jirapi.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
