before_build:
  - nuget restore
artifacts:
  - path: Jirapi.$(APPVEYOR_BUILD_VERSION).nupkg
    name: nuget_pack
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  project: Jirapi.sln
  publish_nuget: true
  publish_nuget_symbols: false
  include_nuget_references: true
  verbosity: minimal
deploy:
  provider: NuGet
  api_key:
    secure: 1EAXx3nmbbCmbltTeDhupKl5fOSOrXuKWvSiAFrBPT2X06JaGhiSS10oG/t8W5AZOF+lTN6222IHssLZm4ffylYXA8ySkJ6wGyjfbzBlKjw=
  artifact: /.*\.nupkg/
  on:
    branch: master